In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')

In [5]:
pd.__version__

'3.0.6'

In [6]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [7]:
df.count

<bound method DataFrame.count of       model_year  origin fuel_type         drivetrain  num_doors  \
0           2006  Europe  Gasoline  Front-wheel drive          4
1           2008  Europe    Diesel  Front-wheel drive          4
2           1996    Asia  Gasoline  Front-wheel drive          5
3           1989  Europe  Gasoline  Front-wheel drive          4
4           1994     USA    Diesel  Front-wheel drive          3
...          ...     ...       ...                ...        ...
9995        2005     USA  Gasoline    All-wheel drive          4
9996        1993    Asia  Gasoline    All-wheel drive          2
9997        2014     USA  Gasoline    All-wheel drive          3
9998        2004     USA    Hybrid   Rear-wheel drive          5
9999        2011     USA    Diesel  Front-wheel drive          4

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                    2180              6       243.0            3870
1                    2390              6       272.0            4210
2                    2320              6       267.0            4240
3                    2130              6       258.0            4490
4                    2580              7       304.0            4510
...                   ...            ...         ...             ...
9995                 2470              6       271.0            4690
9996                 2300              6       244.0            4370
9997                 2480              6       267.0            4590
9998                 2180              6       270.0            4450
9999                 2380              6       295.0            4370

      acceleration  fuel_efficiency_mpg
0              NaN                 31.9
1              NaN                 31.3
2             17.3                 27.5
3             18.7                 28.5
4             17.5                 31.0
...            ...                  ...
9995          18.9                 27.4
9996          19.0                 30.0
9997          18.4                 28.1
9998          20.9                 32.2
9999          17.6                 30.2

[10000 rows x 11 columns]>

In [8]:
len(df)

10000

In [9]:
df.nunique()

model_year              50
origin                   3
fuel_type                3
drivetrain               3
num_doors                4
engine_displacement    127
num_cylinders            5
horsepower             153
vehicle_weight         176
acceleration            93
fuel_efficiency_mpg    188
dtype: int64

In [10]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [11]:
df.describe().round(2)

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.00,10000.00,10000.00,10000.00,9123.00,10000.00,9736.00,10000.00
mean,1999.55,3.50,2268.81,6.04,254.45,4286.75,18.89,30.00
std,14.21,0.95,183.45,0.54,22.84,266.21,1.28,2.93
min,1975.00,2.00,1590.00,4.00,171.00,3320.00,14.00,19.80
25%,1987.00,3.00,2150.00,6.00,239.00,4110.00,18.00,28.00
50%,2000.00,4.00,2270.00,6.00,254.00,4280.00,18.90,30.00
75%,2012.00,4.00,2390.00,6.00,270.00,4470.00,19.70,31.90
max,2024.00,5.00,3110.00,8.00,334.00,5460.00,23.80,41.20

In [12]:
median_horp = df['horsepower'].median()
print(median_horp)

254.0

In [13]:
mode_horp = df['horsepower'].mode()
print(mode_horp)

0    252.0
Name: horsepower, dtype: float64

In [14]:
df['horsepower'].value_counts().head()

horsepower
252.0    174
246.0    168
256.0    168
259.0    165
253.0    165
Name: count, dtype: int64

In [15]:
df['horsepower'].isnull().sum()

np.int64(877)

In [16]:
df['horsepower'] = df['horsepower'].fillna(mode_horp)

In [17]:
nova_mediana_horp = df['horsepower'].median()
print(nova_mediana_horp)

254.0

In [18]:
carros_asia = df[df['origin'] == 'Asia']
carros_asia

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [19]:
carros_asia = carros_asia[['vehicle_weight', 'model_year']]
carros_asia

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [20]:
carros_asia = carros_asia.head(7)
carros_asia

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [21]:
X = carros_asia.values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [22]:
XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [23]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [24]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [25]:
w = XTX_inv.dot(X.T).dot(y)
w

array([0.13644777, 0.2327492 ])

In [26]:
w.sum()

np.float64(0.36919696904925486)

In [27]:
round(w.sum(), 3)

np.float64(0.369)